start /wait cinst 7zip
start /wait cinst fiddler
start /wait cinst filezilla
start /wait cinst adobereader
start /wait cinst vlc
start /wait cinst paint.net
start /wait cinst windirstat
start /wait cinst autohotkey
start /wait cinst procexp
start /wait cinst isorecorder
start /wait cinst windowslivewriter
start /wait cinst puretext